### ISSUE TITLE
suppress error for `rm -rf` on non-existent files

### ISSUE THREAD

**Issue by dakom** [sagiegurari/shell2batch#12]
running `rm -rf` on a non-existent directory gives an error

would be nice if the default could be in that case to not have an error (rather than needing to do conditional checks before running, for use in `cargo-make`)

**Comment by sagiegurari** [comment]
you see the error on linux or windows? can you provide the error?

**Comment by dakom** [comment]
Windows

```
The system cannot find the file specified.
[cargo-make] ERROR - Error while executing command, exit code: 2
```

**Comment by dakom** [comment]
The toml (from `cargo-make`) is:

```
[tasks.clean-rust]
script_runner = "@shell"
script = ["rm -rf ./rust/pkg"]
```

Resulting command is
```
rmdir /S /Q .\rust\pkg
```

**Comment by sagiegurari** [comment]
you can add a condition to the task "file_exists" so this will only execute if the dir exists

**Comment by dakom** [comment]
is there a way to add a condition to each line in a task?

Right now I'm doing this, as a workaround... kinda ugly imho:

```toml
[tasks.clean-rust]
run_task = [{name = [
    "clean-rust1", 
    "clean-rust2",
    "clean-rust3",
]}]

[tasks.clean-rust1]
script_runner = "@shell"
script = ["rm -rf ./_static/wasm/core/pkg"]
condition = {files_exist = ["./_static/wasm/core/pkg"]}

[tasks.clean-rust2]
script_runner = "@shell"
script = ["rm -rf ./rust/target"]
condition = {files_exist = ["./rust/target"]}

[tasks.clean-rust3]
script_runner = "@shell"
script = ["rm -rf ./rust/pkg"]
condition = {files_exist = ["./rust/pkg"]}
```
