### ISSUE TITLE
cp fails on windows when the path comes from variables

### ISSUE THREAD

**Issue by starccy** [sagiegurari/shell2batch#18]
### Problem
On Windows cmd, `copy` would fail when the path contains `/`, they should be converted to `\`.   
I see there has been implemented: [Convert '/' to '\\' in command arguments](https://github.com/sagiegurari/shell2batch/commit/f4964a08c49b35c84c126d2a6fe0cdd13078bb48).     
However, it still can lead to errors while using variables, because slash inside variables will not be converted.

### To Reproduce
Here is a minimal `Makefile.toml` to reproduce.

```toml
[env]
A_PATH = "folder/inner/test.txt"


[tasks.cp1]  # it's okey
script_runner = "@shell"
script = """
cp folder/inner/test.txt ./
"""


[tasks.cp2] # error because ${A_PATH} will be replace by `folder/inner/test.txt ` without slash converted.
script_runner = "@shell"
script = """
echo ${A_PATH}
cp ${A_PATH} ./
"""
```

> output: [cargo-make] ERROR - Error while executing command, exit code: 1

**Comment by sagiegurari** [comment]
for this use case i suggest duckscript, since basically the variable expansion is up to the OS to do

```toml
[tasks.cp2]
script_runner = "@duckscript"
script = """
echo ${A_PATH}
cp ${A_PATH} ./test.txt
"""
```

if its a glob, take a look at glob_cp
