### ISSUE TITLE
`rm ./build/repalungs-wasm/.gitignore` converts to `rmdir .\build\repalungs-wasm\.gitignore`

### ISSUE THREAD

**Issue by JohnScience** [sagiegurari/shell2batch#20]
### Describe The Bug

`./build/repalungs-wasm/.gitignore` is interpreted as a directory, not a file.

### To Reproduce

Use `rm ./build/repalungs-wasm/.gitignore`.

### Error Stack

Irrelevant

### Code Sample

```toml
# using cargo-make
[tasks.my-task]
script_runner = "@shell"
script = '''
cargo new my_project
rm ./my_project/.gitignore
```
